name: solid_software_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.2

  flutter_test:
    sdk: flutter

  solid_lints: ^0.0.19




flutter:

  uses-material-design: true
